// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(WohnungDb))]
    [Migration("20220203124016_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Data.ProviderHealthEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AllDetailsComlete")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailsLoaded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IdsLoaded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NewIdsLoaded")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProviderHealthLogs");
                });

            modelBuilder.Entity("Data.WohnungEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anschrift")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Balkon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezirk")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Etage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Etagen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Flaeche")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FreiAb")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Geladen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Gemeldet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Gesehen")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Keller")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoadDetailsTries")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MieteKalt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MieteWarm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SucheDetails")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("SucheShort")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ueberschrift")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Wbs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wichtigkeit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WohnungId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Zimmer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "WohnungId")
                        .IsUnique();

                    b.ToTable("Wohnungen");
                });
#pragma warning restore 612, 618
        }
    }
}
