// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(WohnungDb))]
    partial class WohnungDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("Data.WohnungDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anschrift")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Balkon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezirk")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Etage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Etagen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Flaeche")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FreiAb")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Keller")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MieteKalt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MieteWarm")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Wbs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WohnungHeaderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Zimmer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WohnungHeaderId");

                    b.ToTable("WohnungDetails");
                });

            modelBuilder.Entity("Data.WohnungHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gemeldet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gesehen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TraumWohnung")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WohnungId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "WohnungId")
                        .IsUnique();

                    b.ToTable("WohnungHeaders");
                });

            modelBuilder.Entity("Data.WohnungDetails", b =>
                {
                    b.HasOne("Data.WohnungHeader", "WohnungHeader")
                        .WithMany("Details")
                        .HasForeignKey("WohnungHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WohnungHeader");
                });

            modelBuilder.Entity("Data.WohnungHeader", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
